// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: messages/status.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusMessage) Reset() {
	*x = StatusMessage{}
	mi := &file_messages_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusMessage) ProtoMessage() {}

func (x *StatusMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusMessage.ProtoReflect.Descriptor instead.
func (*StatusMessage) Descriptor() ([]byte, []int) {
	return file_messages_status_proto_rawDescGZIP(), []int{0}
}

func (x *StatusMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_messages_status_proto protoreflect.FileDescriptor

const file_messages_status_proto_rawDesc = "" +
	"\n" +
	"\x15messages/status.proto\")\n" +
	"\rStatusMessage\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessageB\bZ\x06/protob\x06proto3"

var (
	file_messages_status_proto_rawDescOnce sync.Once
	file_messages_status_proto_rawDescData []byte
)

func file_messages_status_proto_rawDescGZIP() []byte {
	file_messages_status_proto_rawDescOnce.Do(func() {
		file_messages_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messages_status_proto_rawDesc), len(file_messages_status_proto_rawDesc)))
	})
	return file_messages_status_proto_rawDescData
}

var file_messages_status_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_messages_status_proto_goTypes = []any{
	(*StatusMessage)(nil), // 0: StatusMessage
}
var file_messages_status_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_messages_status_proto_init() }
func file_messages_status_proto_init() {
	if File_messages_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messages_status_proto_rawDesc), len(file_messages_status_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_status_proto_goTypes,
		DependencyIndexes: file_messages_status_proto_depIdxs,
		MessageInfos:      file_messages_status_proto_msgTypes,
	}.Build()
	File_messages_status_proto = out.File
	file_messages_status_proto_goTypes = nil
	file_messages_status_proto_depIdxs = nil
}
