// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: messages/login.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginUser struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	LoginRequestId string                 `protobuf:"bytes,1,opt,name=LoginRequestId,proto3" json:"LoginRequestId,omitempty"`
	Username       string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password       string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LoginUser) Reset() {
	*x = LoginUser{}
	mi := &file_messages_login_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUser) ProtoMessage() {}

func (x *LoginUser) ProtoReflect() protoreflect.Message {
	mi := &file_messages_login_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUser.ProtoReflect.Descriptor instead.
func (*LoginUser) Descriptor() ([]byte, []int) {
	return file_messages_login_proto_rawDescGZIP(), []int{0}
}

func (x *LoginUser) GetLoginRequestId() string {
	if x != nil {
		return x.LoginRequestId
	}
	return ""
}

func (x *LoginUser) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginUser) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	LoginRequestId string                 `protobuf:"bytes,1,opt,name=LoginRequestId,proto3" json:"LoginRequestId,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Token          string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_messages_login_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_login_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_messages_login_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetLoginRequestId() string {
	if x != nil {
		return x.LoginRequestId
	}
	return ""
}

func (x *LoginResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_messages_login_proto protoreflect.FileDescriptor

const file_messages_login_proto_rawDesc = "" +
	"\n" +
	"\x14messages/login.proto\"k\n" +
	"\tLoginUser\x12&\n" +
	"\x0eLoginRequestId\x18\x01 \x01(\tR\x0eLoginRequestId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"e\n" +
	"\rLoginResponse\x12&\n" +
	"\x0eLoginRequestId\x18\x01 \x01(\tR\x0eLoginRequestId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05tokenB\bZ\x06/protob\x06proto3"

var (
	file_messages_login_proto_rawDescOnce sync.Once
	file_messages_login_proto_rawDescData []byte
)

func file_messages_login_proto_rawDescGZIP() []byte {
	file_messages_login_proto_rawDescOnce.Do(func() {
		file_messages_login_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messages_login_proto_rawDesc), len(file_messages_login_proto_rawDesc)))
	})
	return file_messages_login_proto_rawDescData
}

var file_messages_login_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_messages_login_proto_goTypes = []any{
	(*LoginUser)(nil),     // 0: LoginUser
	(*LoginResponse)(nil), // 1: LoginResponse
}
var file_messages_login_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_messages_login_proto_init() }
func file_messages_login_proto_init() {
	if File_messages_login_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messages_login_proto_rawDesc), len(file_messages_login_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_login_proto_goTypes,
		DependencyIndexes: file_messages_login_proto_depIdxs,
		MessageInfos:      file_messages_login_proto_msgTypes,
	}.Build()
	File_messages_login_proto = out.File
	file_messages_login_proto_goTypes = nil
	file_messages_login_proto_depIdxs = nil
}
